[env:cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
; CoreS3's PlatformIO board definition uses qio_qspi PSRAM.
; Overriding memory_type to qio_opi makes PSRAM unavailable on this board.
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DARDUINO_LOOP_STACK_SIZE=16384
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -I.pio/libdeps/cores3/M5Utility/src
lib_deps =
    m5stack/M5Unified@0.2.20
    https://github.com/uezo/AIAvatarStackChan.git#0.1.3
    m5stack/M5Utility
