[env:m5stack-stopwatch]
platform = espressif32 @ 6.12.0
board = esp32s3box
framework = arduino
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DARDUINO_LOOP_STACK_SIZE=16384
    -DESP32S3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -I.pio/libdeps/m5stack-stopwatch/M5Utility/src
lib_deps =
    m5stack/M5Unified@0.2.20
    https://github.com/uezo/AIAvatarStackChan.git#0.1.4
    m5stack/M5Utility
